version: '3.8'

services:
  app:
    build: .
    container_name: orderlogic_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - app_network

  webserver:
    image: nginx:alpine
    container_name: orderlogic_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: orderlogic_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orderlogic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
